// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL81Zfus3SN2vNT6fsNiMhySPq1aQ7b_M',
    appId: '1:529049781082:web:f3609b22feea2672ec6963',
    messagingSenderId: '529049781082',
    projectId: 'renewmarket-fa794',
    authDomain: 'renewmarket-fa794.firebaseapp.com',
    storageBucket: 'renewmarket-fa794.firebasestorage.app',
    measurementId: 'G-1HK2K2XH7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSx-DnH6XLIEpOBZ8LasJAFNLUQMvKvo',
    appId: '1:529049781082:android:dba578296cfdd756ec6963',
    messagingSenderId: '529049781082',
    projectId: 'renewmarket-fa794',
    storageBucket: 'renewmarket-fa794.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrVUS17UnQ3YDPGx-wCP8hAfySjMn5ieM',
    appId: '1:529049781082:ios:66f9bff52383f9b1ec6963',
    messagingSenderId: '529049781082',
    projectId: 'renewmarket-fa794',
    storageBucket: 'renewmarket-fa794.firebasestorage.app',
    iosBundleId: 'com.example.renewMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrVUS17UnQ3YDPGx-wCP8hAfySjMn5ieM',
    appId: '1:529049781082:ios:66f9bff52383f9b1ec6963',
    messagingSenderId: '529049781082',
    projectId: 'renewmarket-fa794',
    storageBucket: 'renewmarket-fa794.firebasestorage.app',
    iosBundleId: 'com.example.renewMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL81Zfus3SN2vNT6fsNiMhySPq1aQ7b_M',
    appId: '1:529049781082:web:8d7d3de1e5a3cd56ec6963',
    messagingSenderId: '529049781082',
    projectId: 'renewmarket-fa794',
    authDomain: 'renewmarket-fa794.firebaseapp.com',
    storageBucket: 'renewmarket-fa794.firebasestorage.app',
    measurementId: 'G-L1VZNEF7C2',
  );
}
